### ISSUE TITLE
wad fails to compile

### ISSUE THREAD

**Issue by NoShotz** [chaoticgd/wrench#174]
![image](https://user-images.githubusercontent.com/13302841/162100120-498f9bb7-2c4e-4b53-b8f6-8cd9e8a55254.png)

**Comment by chaoticgd** [comment]
This look like it might be due to an old compiler version (or maybe a newer one?), it would be useful to note that below. At any rate, I've decided to remove the bitfields since I remember them causing trouble for someone else as well (though in that case making them unsigned fixed it, also on VS) and they're not really helping anything.

**Comment by NoShotz** [comment]
This is the version I have

`Microsoft (R) C/C++ Optimizing Compiler Version 19.24.28314 for x86`
